sudo: false
language: go
go:
  - 1.5.1
  - tip
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
install:
  - go get golang.org/x/tools/cmd/vet
script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go tool vet .
  - go test -v -race ./...
